use anchor_lang::prelude::*;
use arcium_anchor::{
    queue_computation, ArgBuilder, SIGN_PDA_SEED,
    ARCIUM_CLOCK_ACCOUNT_ADDRESS, ARCIUM_FEE_POOL_ACCOUNT_ADDRESS,
    traits::QueueCompAccs,
};
use arcium_client::idl::arcium::{
    accounts::{MXEAccount, ComputationDefinitionAccount, Cluster, FeePool, ClockAccount},
    cpi::accounts::QueueComputation,
    program::Arcium,
    types::{CallbackInstruction, CallbackAccount},
    ID_CONST as ARCIUM_PROG_ID,
};
use arcium_client::pda as arcium_pda;

use crate::state::*;
use crate::state::crank_tally::try_record_crank_action;
use crate::errors::PokerError;
use crate::constants::*;
use crate::instructions::init_comp_defs::COMP_DEF_OFFSET_SHUFFLE;
use crate::ID as PROGRAM_ID;

/// Queue MPC shuffle_and_deal computation via Arcium.
/// Transitions Starting → AwaitingDeal.
///
/// Manual QueueCompAccs implementation since #[arcium_program] macro
/// conflicts with session-keys.
///
/// PERMISSIONLESS — anyone can call when phase is Starting.

/// ArciumSignerAccount — simple PDA that stores the bump seed.
/// Normally generated by #[arcium_program] macro; defined manually here.
/// Seeds: [b"ArciumSignerAccount"] under OUR program ID.
#[account]
pub struct ArciumSignerAccount {
    pub bump: u8,
}

#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct ArciumDeal<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        init_if_needed,
        space = 9,
        payer = payer,
        seeds = [SIGN_PDA_SEED],
        bump,
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,

    #[account(address = arcium_pda::mxe_acc(&PROGRAM_ID))]
    pub mxe_account: Account<'info, MXEAccount>,

    /// CHECK: mempool — validated by address constraint
    #[account(mut)]
    pub mempool_account: UncheckedAccount<'info>,

    /// CHECK: executing_pool — validated by address constraint
    #[account(mut)]
    pub executing_pool: UncheckedAccount<'info>,

    /// CHECK: computation_account — validated by Arcium CPI
    #[account(mut)]
    pub computation_account: UncheckedAccount<'info>,

    #[account(
        address = arcium_pda::computation_definition_acc(&PROGRAM_ID, COMP_DEF_OFFSET_SHUFFLE),
    )]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,

    #[account(mut)]
    pub cluster_account: Account<'info, Cluster>,

    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,

    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,

    pub arcium_program: Program<'info, Arcium>,

    // ── FastPoker game accounts ──

    #[account(
        mut,
        seeds = [TABLE_SEED, table.table_id.as_ref()],
        bump = table.bump,
        constraint = table.phase == GamePhase::Starting @ PokerError::InvalidActionForPhase,
    )]
    pub table: Account<'info, Table>,

    #[account(
        mut,
        seeds = [DECK_STATE_SEED, table.key().as_ref()],
        bump = deck_state.bump,
    )]
    pub deck_state: Box<Account<'info, DeckState>>,

    pub system_program: Program<'info, System>,
}

/// Manual QueueCompAccs implementation
impl<'info> QueueCompAccs<'info> for ArciumDeal<'info> {
    fn comp_def_offset(&self) -> u32 {
        COMP_DEF_OFFSET_SHUFFLE
    }

    fn queue_comp_accs(&self) -> QueueComputation<'info> {
        QueueComputation {
            signer: self.payer.to_account_info(),
            sign_seed: self.sign_pda_account.to_account_info(),
            comp: self.computation_account.to_account_info(),
            mxe: self.mxe_account.to_account_info(),
            executing_pool: self.executing_pool.to_account_info(),
            mempool: self.mempool_account.to_account_info(),
            comp_def_acc: self.comp_def_account.to_account_info(),
            cluster: self.cluster_account.to_account_info(),
            pool_account: self.pool_account.to_account_info(),
            system_program: self.system_program.to_account_info(),
            clock: self.clock_account.to_account_info(),
        }
    }

    fn arcium_program(&self) -> AccountInfo<'info> {
        self.arcium_program.to_account_info()
    }

    fn mxe_program(&self) -> Pubkey {
        PROGRAM_ID
    }

    fn signer_pda_bump(&self) -> u8 {
        self.sign_pda_account.bump
    }
}

pub fn handler(
    ctx: Context<ArciumDeal>,
    computation_offset: u64,
    player_data: Vec<u8>,
    num_players: u8,
) -> Result<()> {
    // Validate before CPI (read-only access)
    require!(num_players >= 2 && num_players <= 9, PokerError::InvalidPlayerCount);
    // player_data = 9 × (32-byte pubkey + 16-byte nonce) = 432 bytes on the heap
    require!(player_data.len() == 9 * 48, PokerError::InvalidPlayerCount);

    // M6: Validate x25519 pubkeys — MPC nodes reject all-zero [0;32] as invalid curve point.
    // Active player slots (0..num_players) MUST have non-zero pubkeys.
    // Empty slots (num_players..9) use dummy non-zero keys provided by the crank.
    for i in 0..9usize {
        let base = i * 48;
        let pubkey = &player_data[base..base + 32];
        require!(pubkey != &[0u8; 32], PokerError::InvalidPlayerCount);
    }
    let hand_number = ctx.accounts.table.hand_number;

    // Set signer PDA bump BEFORE CPI — required for PDA signing in queue_computation.
    // Without this, bump defaults to 0 and PDA derivation fails → PrivilegeEscalation.
    ctx.accounts.sign_pda_account.bump = ctx.bumps.sign_pda_account;

    // Build args + queue CPI in a helper. Data stays on heap (Vec) to avoid
    // SBF 4KB stack overflow that occurs with fixed [[u8;32];9] + [u128;9] args.
    let (_table_key, _deck_state_key) = queue_deal_cpi(
        &ctx, computation_offset, &player_data, num_players,
    )?;

    // Transition phase (mutable borrows after CPI)
    let table = &mut ctx.accounts.table;
    let deck_state = &mut ctx.accounts.deck_state;

    table.phase = GamePhase::AwaitingDeal;
    deck_state.computation_offset = computation_offset;
    deck_state.hand_number = hand_number;
    table.action_nonce = table.action_nonce.wrapping_add(1);

    // Store player x25519 pubkeys + input nonces in DeckState for reveal_showdown.
    // encrypted_hole_cards[0..8] = player pubkeys (32 bytes each)
    // hole_card_nonces[0..8] = player INPUT nonces (16 bytes each)
    // These are needed by arcium_showdown_queue to rebuild the Shared context.
    for i in 0..9usize {
        let base = i * 48;
        let mut pubkey = [0u8; 32];
        pubkey.copy_from_slice(&player_data[base..base + 32]);
        let mut nonce = [0u8; 16];
        nonce.copy_from_slice(&player_data[base + 32..base + 48]);
        deck_state.encrypted_hole_cards[i] = pubkey;
        deck_state.hole_card_nonces[i] = nonce;
    }

    // Record crank action for MPC queue payer (CrankTallyER via remaining_accounts)
    let tkey = table.key();
    let ckey = ctx.accounts.payer.key();
    try_record_crank_action(ctx.remaining_accounts, &tkey, &ckey, hand_number);

    msg!(
        "Queued MPC shuffle_and_deal: hand #{}, {} players, offset={}",
        hand_number, num_players, computation_offset
    );

    Ok(())
}

/// Separated into #[inline(never)] to keep heap data off the main handler stack frame.
/// player_data layout: 9 × (32-byte x25519 pubkey + 16-byte LE nonce) = 432 bytes on heap.
#[inline(never)]
fn queue_deal_cpi(
    ctx: &Context<ArciumDeal>,
    computation_offset: u64,
    player_data: &[u8],
    num_players: u8,
) -> Result<(Pubkey, Pubkey)> {
    // Parse pubkeys + nonces from packed Vec and build MPC args
    // Single MXE nonce (nonce=0) for packed community card output
    let mut builder = ArgBuilder::new()
        .plaintext_u128(0u128);  // mxe nonce (packed community u64)
    for i in 0..9 {
        let base = i * 48;
        let mut pubkey = [0u8; 32];
        pubkey.copy_from_slice(&player_data[base..base + 32]);
        let mut nonce_bytes = [0u8; 16];
        nonce_bytes.copy_from_slice(&player_data[base + 32..base + 48]);
        let nonce = u128::from_le_bytes(nonce_bytes);
        builder = builder
            .x25519_pubkey(pubkey)
            .plaintext_u128(nonce);
    }
    let args = builder.plaintext_u8(num_players).build();

    // Build callback instruction — tells Arcium which instruction to call when MPC completes.
    let table_key = ctx.accounts.table.key();
    let deck_state_key = ctx.accounts.deck_state.key();
    let comp_def_key = ctx.accounts.comp_def_account.key();
    let mxe_key = ctx.accounts.mxe_account.key();
    let cluster_key = ctx.accounts.cluster_account.key();

    // Anchor discriminator = SHA256("global:shuffle_and_deal_callback")[0..8]
    let callback_disc: Vec<u8> = vec![0x3f, 0xdc, 0xcc, 0xd4, 0x4a, 0x91, 0x8a, 0xd1];

    // Build callback account list: named accounts + 9 SeatCards as remaining_accounts
    let mut cb_accounts = vec![
        CallbackAccount { pubkey: ARCIUM_PROG_ID, is_writable: false },
        CallbackAccount { pubkey: comp_def_key, is_writable: false },
        CallbackAccount { pubkey: mxe_key, is_writable: false },
        CallbackAccount { pubkey: ctx.accounts.computation_account.key(), is_writable: false },
        CallbackAccount { pubkey: cluster_key, is_writable: false },
        CallbackAccount { pubkey: anchor_lang::solana_program::sysvar::instructions::ID, is_writable: false },
        CallbackAccount { pubkey: table_key, is_writable: true },
        CallbackAccount { pubkey: deck_state_key, is_writable: true },
    ];
    // Append SeatCards PDAs for seats within the SIZE=320 callback window.
    // Stride-3 layout: only P0+P1 get full encrypted data (Mxe=3 + P0=3 + P1=3 + partial=1 = 10 slots).
    // Including all 9 SeatCards exceeds Solana's 1232-byte TX limit ("Output too large").
    // Callback handler already handles player_idx >= seat_cards_accounts.len() by skipping.
    let seats_in_callback = std::cmp::min(ctx.accounts.table.max_players, 2);
    for i in 0..seats_in_callback {
        let (seat_cards_pda, _) = Pubkey::find_program_address(
            &[SEAT_CARDS_SEED, table_key.as_ref(), &[i]],
            &PROGRAM_ID,
        );
        cb_accounts.push(CallbackAccount { pubkey: seat_cards_pda, is_writable: true });
    }

    let callbacks = vec![CallbackInstruction {
        program_id: PROGRAM_ID,
        discriminator: callback_disc,
        accounts: cb_accounts,
    }];

    // CPI to Arcium queue_computation (must happen before mutable borrows on table/deck_state)
    queue_computation(
        ctx.accounts,
        computation_offset,
        args,
        callbacks,
        1,  // num_callback_txs
        0,  // cu_price_micro
    )?;

    Ok((table_key, deck_state_key))
}
